### PR TITLE
#4608 Adding styles for one column in expanded area

### LINKED ISSUE #4608: 1 Column is not working in Expanded widget preview menu configuration
## To Reproduce

Step-by-step instructions to reproduce the behavior:

1. Add a New Area type
2. set `expanded: true` and `columns: 1`
3. Open that expanded menu on the UI
4. Notice that all widgets inside that area are stacked together

**Version of Node.js:**
20.15.0

**Server Operating System:**
Windows

**Screenshots**
image

### PR DESCRIPTION
**Pull request by harshmehta813**
## Summary

"Closes #4608 "*

## What are the specific steps to test this change?

> 1. Add a New Area type
> 2. set expanded: true and columns: 1
> 3. Open that expanded menu on the UI
> 4. Check that there should be only 1 column and only 1 widget in each row.

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [x] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue [hunk 1]
```diff
@@ -220,6 +220,12 @@ export default {
     background-color: var(--a-base-10);
   }
 
+  &--1-column {
+    display: grid;
+    grid-template-columns: repeat(1, 1fr);
```
Comment (BoDonkey) [inline modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue:225]:
```suggestion
    grid-template-columns: 1fr;
```
No real need for the `repeat`, this is cleaner.

**Review by BoDonkey — CHANGES_REQUESTED** [review]
Small nitpicky change - thanks!!

**Review by BoDonkey — DISMISSED** [review]
Thank you!

**Review by BoDonkey — APPROVED** [review]
