### PR TITLE
Applies slug field default values to their slugify options

### LINKED ISSUE #3586: Impossible to have slug fields that stay empty
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

1. Create a schema (on a piece type, for example) with a `slug` type field separate from any doc type slug. It should not follow any other fields.
2. Include `def: ''` on the field.
3. Edit that document in the UI and don't enter anything in the slug field.

## Expected behavior
The field value should be empty. Either `null` or an empty string.

## Describe the bug
The string "none" is saved instead. This is because the slug schema field settings run the empty entry through sluggo without passing the field's default value as the sluggo string default.

Arguably the field should stay empty regardless of the field's `def` value (including no value) unless it is following another field.

### PR DESCRIPTION
**Pull request by abea**
Closes #3586

------------------

Please ensure your pull request follows these guidelines:

- [x] Link to the related issue with requirements and/or clearly describe 1) what problem this solves and 2) the requirements to review it against.
- [x] Update the `CHANGELOG.md` file with the added feature or fix. If there is not yet a heading for an upcoming release, add one following the established pattern.
- [x] Keep the pull request minimal! Break large updates into separate pull requests for individual features/fixes whenever possible. Small requests get reviewed more quickly.
- [x] All tests must pass, including the linters. Run `npm run lint` to test code linting independently.

Thanks for contributing!

### CODE REVIEW

**Comment by abea** [comment]
I realize this might seem like a BC break. It really seems like a bug if "none" starts populating in fields that had no value.

File: modules/@apostrophecms/schema/index.js [hunk 1]
```diff
@@ -142,11 +142,14 @@ module.exports = {
       // leading slash required). Otherwise, expect a object-style slug
       // (no slashes at all)
       convert: function (req, field, data, destination) {
-        const options = {};
+        const options = {
+          def: field.def !== undefined ? field.def : undefined
```
Comment (boutell) [inline modules/@apostrophecms/schema/index.js:146]: Seems like this must be equivalent to `def: field.def` since you handle undefined by passing undefined.

**Review by boutell — CHANGES_REQUESTED** [review]

File: modules/@apostrophecms/schema/index.js (hunk 1 above)
Comment (abea) [reply modules/@apostrophecms/schema/index.js:146]: oh, true.

**Review by boutell — APPROVED** [review]
