### PR TITLE
PRO-2502: Resolve _urls by default

### LINKED ISSUE #3643: Regression : the `_urls` field is not given in the JSON response after API call on a piece
## To Reproduce

I started from the out-of-the-box a3-boilerplate project, then used the following piece-type : 

```javascript
module.exports = {
  extend: "@apostrophecms/piece-type",
  options: {
    label: "Élément du Carrousel",
    pluralLabel: "Éléments du Carrousel",
    publicApiProjection: {
      title: 1,
      theme: 1,
      body: 1,
      _cover: 1,
      actionButtonUrl: 1,
      actionButtonText: 1,
      type: 1, // This is mandatory. See issue https://github.com/apostrophecms/apostrophe/issues/3626
    },
  },
  fields: {
    add: {
      title: {
        required: true,
        label: "Titre principal",
        type: "string",
        help: 'Le titre principal de la slide.',
      },
      theme: {
        required: true,
        label: "Thème principal",
        type: "string",
        help: 'Un ou des thèmes, des mots clés, des hashtag...',
      },
      body: {
        required: true,
        label: "Descriptif",
        type: "area",
        help: 'Le contenu de ce qui sera affiché sur la slide.',
        options: {
          max: 1,
          widgets: {
            "@apostrophecms/rich-text": {
              // Toolbar configuration
              toolbar: ["styles", "bold", "italic"],
              // Styles configuration
              styles: [
                {
                  tag: "p",
                  label: "Paragraph (P)",
                },
              ],
            },
          },
        },
      },
      _cover: {
        required: true,
        label: "Image de fond",
        help: 'L\'image de fond de la slide. Il faut une image au format paysage, de bonne qualité.',
        type: 'relationship',
        withType: '@apostrophecms/image',
        max: 1,
      },
      actionButtonUrl: {
        label: "Url du bouton d'action (Optionnel)",
        help: 'Si renseigné, un bouton d\'action apparaîtra sur la slide, pointant vers une URL à renseigner ici. Ex : /#footer',
        type: "url",
      },
      actionButtonText: {
        label: "Texte du bouton d'action (Requis si url renseignée)",
        help: 'Le texte du bouton d\'action qui s\'affichera sur la slide.',
        type: "string",
      },
    },
    group: {
      jobDescriptionFields: {
        label: "Élément du carrousel",
        fields: [
          "title",
          "theme",
          "body",
          "_cover",
          "actionButtonUrl",
          "actionButtonText",
        ],
      },
    },
  },
};

```

After that I run `npm run dev` and go to `http://localhost:3001/api/v1/homeLandingCarousel`

Here is the returned payload : 

```javascript
{
  "pages": 1,
  "currentPage": 1,
  "results": [
    {
      "_id": "ckyx397bk000fm8awbar2gb8k:en:published",
      "aposDocId": "ckyx397bk000fm8awbar2gb8k",
      "aposLocale": "en:published",
      "lastPublishedAt": "2022-01-27T14:45:33.775Z",
      "slug": "gfdgd",
      "visibility": "public",
      "title": "gfdgd",
      "theme": "fdg",
      "body": {
        "_id": "ckyx38dx4000s266gp9n0j3ib",
        "items": [
          {
            "_id": "ckyx38g8k001c266ghd93nvk2",
            "metaType": "widget",
            "type": "@apostrophecms/rich-text",
            "content": "<p>dfgdfg</p>",
            "_edit": true,
            "_docId": "ckyx397bk000fm8awbar2gb8k:en:published"
          }
        ],
        "metaType": "area",
        "_edit": true,
        "_docId": "ckyx397bk000fm8awbar2gb8k:en:published"
      },
      "actionButtonUrl": "dfg",
      "actionButtonText": "gdgdg",
      "archived": false,
      "type": "homeLandingCarousel",
      "aposMode": "published",
      "metaType": "doc",
      "createdAt": "2022-01-27T14:45:33.776Z",
      "updatedAt": "2022-01-27T14:45:33.777Z",
      "updatedBy": {
        "_id": "ckyx2yc7b0004u4awa75ow7xm",
        "title": "my-user",
        "username": "my-user"
      },
      "titleSortified": "gfdgd",
      "highSearchText": "gfdgd gfdgd",
      "highSearchWords": [
        "gfdgd"
      ],
      "lowSearchText": "gfdgd gfdgd dfgdfg",
      "searchSummary": "\ndfgdfg",
      "coverIds": [
        "ckyx38tuk0007m8awc0oup488"
      ],
      "_edit": true,
      "_publish": true,
      "_cover": [
        {
          "_id": "ckyx38tuk0007m8awc0oup488:en:published",
          "aposDocId": "ckyx38tuk0007m8awc0oup488",
          "aposLocale": "en:published",
          "lastPublishedAt": "2022-01-27T14:45:21.098Z",
          "slug": "image-carbon-closup",
          "attachment": {
            "_id": "ckyx38n9c0006m8awue8rc2to",
            "crop": null,
            "group": "images",
            "createdAt": "2022-01-27T14:45:15.869Z",
            "name": "carbon-closup",
            "title": "carbon closup",
            "extension": "jpg",
            "type": "attachment",
            "docIds": [
              "ckyx38tuk0007m8awc0oup488:en:draft",
              "ckyx38tuk0007m8awc0oup488:en:published"
            ],
            "archivedDocIds": [],
            "length": 1439019,
            "md5": "b2ec3bab47879bc771aeffe8d292eb3d",
            "width": 2883,
            "height": 1920,
            "landscape": true,
            "used": true,
            "utilized": true,
            "archived": false
          },
          "title": "carbon closup",
          "alt": "",
          "credit": "",
          "creditUrl": null,
          "archived": false,
          "type": "@apostrophecms/image",
          "aposMode": "published",
          "metaType": "doc",
          "createdAt": "2022-01-27T14:45:16.008Z",
          "titleSortified": "carbon closup",
          "updatedAt": "2022-01-27T14:45:21.146Z",
          "updatedBy": {
            "_id": "ckyx2yc7b0004u4awa75ow7xm",
            "title": "my-user",
            "username": "my-user"
          },
          "highSearchText": "carbon closup image carbon closup",
          "highSearchWords": [
            "carbon",
            "closup",
            "image"
          ],
          "lowSearchText": "carbon closup image carbon closup",
          "searchSummary": "",
          "tagsIds": [],
          "visibility": "public",
          "_edit": true,
          "_publish": true
        }
      ]
    }
  ]
}
```

## Details

**Version of Node.js:**
Node.js 16.13.2, Apostrophe 3.12.0, MongoDB 5.0.5

**Server Operating System:**
Windows 10

### PR DESCRIPTION
**Pull request by myovchev**
## Summary

Resolve attachment owned `_urls` for API calls.

Closes #3643 
Closes PRO-2502
Related to https://github.com/apostrophecms/apostrophe/pull/3525

## What are the specific steps to test this change?
Attachment URLs are computed by default.

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [x] Related tests have been updated

### CODE REVIEW

File: test/pieces-public-api.js [hunk 1]
```diff
@@ -151,4 +159,80 @@ describe('Pieces Public API', function() {
     delete apos.thing.options.cache;
   });
 
+  it('should resolve _urls for image attachments', async () => {
```
Comment (boutell) [inline test/pieces-public-api.js:162]: Please no arrow functions in mocha.

**Review by boutell — CHANGES_REQUESTED** [review]

**Review by boutell — APPROVED** [review]
