### PR TITLE
fix #3667

### LINKED ISSUE #3667: Parked pages' children are not localized properly
## Describe the bug

I added a parked page with children in this way:
```
{
    parkedId: '',
    type: '',
    slug: '',
    _defaults: {
      title: ''
    },
    _children: [
         {
            parkedId: '',
            type: '',
            slug: ',
            _defaults: {
               title: ''
          }
     }]
 }
```
In my project I have a few locales. It properly created pages in every locale and these pages were properly localized.

In CMS:
obraz

But I found a problem with these pages children. Pages were properly added, but they're not localized correctly. In the CMS I see
obraz

## Expected behavior

Children pages have the same localization as parents

## Details
* Apostrophe: 3.14.0
* Node.js: 17.3.0

### PR DESCRIPTION
**Pull request by boutell**
Also the needed migration resolves a different one-off problem for an enterprise client. Try to prevent the one-off from recurring with better locking

## Summary

* Fixes a nasty bug where use of `_children` with parked pages broke replication in multi-locale websites.
* Introduces tons of tests to make sure we avoid regressions in the parked page logic.
* The necessary migration also resolves a once-seen problem where the draft and published aposDocIds were not in sync on a single-locale site for a parked page. But we have been unable to replicate that problem on a new site or via highly creative unit tests. So there could be more work later if it ever recurs and we nail down the cause.
* Wraps a lock around more of the startup logic to further reduce the risk of race conditions.

## What are the specific steps to test this change?

Sync down WL, npm run dev, the sandbox site works now. (I tested this, you don't have to, we will validate it on the demo after merge.)

## What kind of change does this PR introduce?
*(Check at least one)*

- [X] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [X] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: modules/@apostrophecms/migration/index.js [hunk 1]
```diff
@@ -231,41 +231,36 @@ module.exports = {
       // Perform the actual migrations. Implementation of
       // the @apostrophecms/migration:migrate task
       async migrate(options) {
-        await self.apos.lock.lock(self.__meta.name);
```
Comment (boutell) [inline modules/@apostrophecms/migration/index.js:234]: All I did here was remove the lock because I moved it up a level. Removing the try block resulted in github thinking this is very exciting but it's not.

File: modules/@apostrophecms/page/index.js [hunk 2]
```diff
@@ -2187,7 +2188,47 @@ database.`);
...
+      addMisreplicatedParkedPagesMigration() {
+        self.apos.migration.add('misreplicated-parked-pages', async () => {
+          const parkedPages = await self.apos.doc.db.find({
+            parkedId: {
+              $exists: 1
+            }
+          }).toArray();
+          let locales = Object.keys(self.apos.i18n.locales);
+          if (locales[0] !== self.apos.i18n.defaultLocale) {
+            locales = [ self.apos.i18n.defaultLocale, ...locales.filter(locale => locale !== self.apos.i18n.defaultLocale) ];
```
Comment (gregvanbrug) [inline modules/@apostrophecms/page/index.js:2201]: What you have is fine but believe you could also do something like below if you wanted to avoid filtering since you're just rearranging the array.
```
locales = [ ...new Set([ self.apos.i18n.defaultLocale, ...locales ])
```
Might not even need to do the check if you're setting the order yourself.

File: modules/@apostrophecms/page/index.js [hunk 3]
```diff
@@ -2187,7 +2188,47 @@ database.`);
...
+          }
+          const parkedIds = [ ...new Set(parkedPages.map(page => page.parkedId)) ];
```
Comment (gregvanbrug) [inline modules/@apostrophecms/page/index.js:2203]: Aren't `parkedIds` supposed to be unique?

File: test/parked-pages.js [hunk 4]
```diff
@@ -58,5 +88,246 @@ describe('Parked Pages', function() {
...
+
+async function validate(apos, expected) {
+  const locales = Object.keys(apos.i18n.locales);
+  const slugs = await apos.doc.db.distinct('slug', {
+    slug: /^\//
+  });
+  slugs.sort();
+  assert.deepStrictEqual(slugs, expected);
+  const pages = await apos.doc.db.find({
+    slug: /^\//
```
Comment (gregvanbrug) [inline test/parked-pages.js:284]: Maybe only relevant to the tests but does a parked slug always start with `/`?

**Review by gregvanbrug — CHANGES_REQUESTED** [review]
Looks good. Just couple little things to confirm.

File: modules/@apostrophecms/page/index.js (hunk 2 above)
Comment (boutell) [reply modules/@apostrophecms/page/index.js:2201]: Right about all of the above, I didn't internalize enough everything set does for me.

File: modules/@apostrophecms/page/index.js (hunk 3 above)
Comment (boutell) [reply modules/@apostrophecms/page/index.js:2203]: They are unique within a locale + mode combo, but intentionally not so across locales, as there's always a draft for every published version, and (for parked pages, not everything) always an fr for every en, etc.

File: test/parked-pages.js (hunk 4 above)
Comment (boutell) [reply test/parked-pages.js:284]: Yes, only pages can be parked and "slug starts with a slash" is a guarantee we stand by for pages.

**Review by gregvanbrug — DISMISSED** [review]

**Review by gregvanbrug — APPROVED** [review]
