### PR TITLE
PRO-2173 Properly displays UI strings with colons.

### LINKED ISSUE #3475: 3.5: help/htmlHelp broken by http(s):
## To Reproduce

Add html help to a field `htmlHelp: '<a href="https://google.com">Test html</a>'`
The result in admin UI is everything before `https:` is cut off. The visible result is `//google.com">Test html`
The same applies if just`http:` or `https:` are present in both `help` and `htmlHelp`.
Example: `help: 'A link to https://google.com'` renders `//google.com` 

## Expected behavior
I guess not to do the above :)

## Details
Tested against the `main` branch, post v3.5.0 tag

### PR DESCRIPTION
**Pull request by abea**
## Summary

Closes #3475 
Closes PRO-2173

## What are the specific steps to test this change?

Use `htmlHelp` help text on a doc type field, such as:
```
htmlHelp: 'This link to the <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea" target="_blank">MDN textarea reference</a> should display properly.',
```

In the main branch this will only display the part after the colon. With this branch it will display that properly as HTML with a link. 

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [x] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: modules/@apostrophecms/ui/ui/apos/lib/i18next.js [hunk 1]
```diff
@@ -23,6 +23,14 @@ export default {
       debug: i18n.debug,
       interpolation: {
         escapeValue: false
+      },
+      appendNamespaceToMissingKey: true,
+      parseMissingKeyHandler (key) {
+        if (key.startsWith(`${this.defaultNS[0]}:`)) {
```
Comment (boutell) [inline modules/@apostrophecms/ui/ui/apos/lib/i18next.js:29]: This only checks for the default namespace. We must make sure it is not any of the namespaces that were pushed to the browser (think of admin UI for non-core modules). Which can be done, see these loops from the same file, note the `addResourceBundle` calls all of which take an `ns` parameter, wrap that to make note of these and you'll have something to check against that covers all the cases.

```
    for (const [ ns, phrases ] of Object.entries(i18n.i18n[i18n.locale])) {
      i18next.addResourceBundle(i18n.locale, ns, phrases, true, true);
    }
    if (i18n.locale !== i18n.defaultLocale) {
      for (const [ ns, phrases ] of Object.entries(i18n.i18n[i18n.defaultLocale])) {
        i18next.addResourceBundle(i18n.defaultLocale, ns, phrases, true, true);
      }
    }
    if ((i18n.locale !== 'en') && (i18n.defaultLocale !== 'en')) {
      for (const [ ns, phrases ] of Object.entries(i18n.i18n.en)) {
        i18next.addResourceBundle('en', ns, phrases, true, true);
      }
    }
```

**Review by boutell — CHANGES_REQUESTED** [review]

File: modules/@apostrophecms/ui/ui/apos/lib/i18next.js (hunk 1 above)
Comment (abea) [reply modules/@apostrophecms/ui/ui/apos/lib/i18next.js:29]: The bug only occurs when the key has no namespace and is therefore using the default namespace. If it's an actual l10n key registered on a namespace then it continues through the normal i18n flow and is displayed correctly as the intended text.

If we did apply this to every namespace, then I think we would break localization since it would hit i18next for conversion without the namespace information.

Comment (boutell) [reply modules/@apostrophecms/ui/ui/apos/lib/i18next.js:29]: OK so this code runs only if the key is not found. I get that this doesn't break other namespaces. I still don't quite get what's going on with this if statement though, can you explain?

**Review by boutell — CHANGES_REQUESTED** [review]
Yes, we know the string should be treated as having the default namespace,

File: modules/@apostrophecms/ui/ui/apos/lib/i18next.js (hunk 1 above)
Comment (boutell) [reply modules/@apostrophecms/ui/ui/apos/lib/i18next.js:29]: Also how will this fix play out if the argument *is* a namespaced key, but the translation just hasn't been written yet?

Comment (abea) [reply modules/@apostrophecms/ui/ui/apos/lib/i18next.js:38]: Normally i18next displays unrecognized l10n keys by themselves. This includes strings never meant to be keys (where l10n isn't actively in use), e.g., "Not meant to be localized."

With `appendNamespaceToMissingKey: true`, both the key and the namespace are displayed. Example: "translation:Not meant to be localized"). That means that strings containing colons will be passed through fully and not chopped at the colon (such as URLs).

When no namespace is provided, the default namespace is used ("translation," by default). If a namespace is used, i18next will attempt to find the key in the namespace and display the proper value.

We don't want to print something like "translation:Not meant to be localized." So if we see the "key" starts with the default namespace, we slice that off the string and pass the rest of the string along to be displayed.

Comment (abea) [reply modules/@apostrophecms/ui/ui/apos/lib/i18next.js:38]: > Also how will this fix play out if the argument is a namespaced key, but the translation just hasn't been written yet?

It will use the fallback locales as normal. Removing the Spanish `managePages` key entry will use the English entry.

**Review by boutell — APPROVED** [review]

**Comment by boutell** [comment]
Cool, sounds like you managed to same some effort over my original plan.

**Comment by boutell** [comment]
Cool, sounds like you managed to same some effort over my original plan.

**Review by boutell — APPROVED** [review]
